version: "3.9"

services:
  web-app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: web-app-tantradjango
    command: poetry run gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: db-postgres-tantra
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  nginx:
    build: ./nginx
    restart: unless-stopped
    volumes:
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    ports:
      - "80:80"
    depends_on:
      - web-app

volumes:
  postgres_data:
  static_volume:
  media_volume: