version: "3.9"

services:
  web-app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: web-app-tantradjango
    command: poetry run python manage.py runserver 0.0.0.0:8000

    volumes:
      - ./app:/home/app
      - ./app:/home/app
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: db-postgres-tantra
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME-tantra_db}
      POSTGRES_USER: ${DB_USER-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD-postgres}



volumes:
  postgres_data: