# Generated by Django 5.0 on 2024-01-08 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_feature_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'удобство', 'verbose_name_plural': 'удобства'},
        ),
    ]
