# Generated by Django 5.0 on 2024-01-11 19:25

import autoslug.fields
import django.db.models.deletion
import imagekit.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('body', models.TextField(verbose_name='Текст')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='articles/%Y/%m', verbose_name='фото')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_modified', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения')),
                ('place', models.CharField(blank=True, help_text='Место проведения', max_length=100, null=True, verbose_name='Место')),
                ('event_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время мероприятия')),
            ],
            options={
                'verbose_name': 'Анонс',
                'verbose_name_plural': 'Анонсы',
                'ordering': ['-event_time'],
                'get_latest_by': 'event_time',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('body', models.TextField(verbose_name='Текст')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='articles/%Y/%m', verbose_name='фото')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_modified', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', related_query_name='article', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-date_added'],
                'get_latest_by': 'date_added',
            },
        ),
    ]
