# Generated by Django 5.0 on 2024-01-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0002_auto_20231230_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialistprofile',
            name='whatsapp_profile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Whatsapp'),
        ),
    ]
